### ISSUE TITLE
Go SDK does not compile

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-akamai#131]
### What happened?

The Go code generated for this provider does not compile. This probably will be fixed by moving up to a newer pulumi/pkg version.

### Steps to reproduce

    cd sdk/go && go build -v all

### Expected Behavior

Go code builds

### Actual Behavior

GO compiler error

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Still an issue on 3.51.0 https://github.com/pulumi/pulumi-akamai/pull/132

**Comment by abhinav** [comment]
```
% go build
# github.com/pulumi/pulumi-akamai/sdk/v4/go/akamai
./propertyVariables.go:19:12: undefined: PropertyVariablesVariableArrayOutput
./propertyVariables.go:60:14: undefined: PropertyVariablesVariable
./propertyVariables.go:67:12: undefined: PropertyVariablesVariableArrayInput
./propertyVariables.go:76:14: undefined: PropertyVariablesVariable
./propertyVariables.go:82:12: undefined: PropertyVariablesVariableArrayInput
```

These types were deleted in #93.
"akamai_property_variables" was added to IgnoreMappings:
https://github.com/pulumi/pulumi-akamai/blob/925eb31c0a58f4882cdb860481a1166fb1f0d449/provider/resources.go#L111-L114

**Comment by t0yv0** [comment]
Got it! Thank for this. Confirmed there's some issue with either makefiles or providers process and these files are not generated by Pulumi code but carry over from the previous time the code was generated. The workaround is:

```
rm -rf sdk/go
make tfgen provider build_sdks
```

I will close the Pulumi issue as invalid.
