### ISSUE TITLE
Update token expire while deactivating property from production

### ISSUE THREAD

**Issue by Hanskun** [pulumi/pulumi-akamai#138]
### What happened?

I have created a new stack with an activated property in staging and production and want to destroy this stack and decomission the corresponding resources in Akamai. The pulumi program is running as it should, but due to deactivation of the production environment taking an extended amount of time I get the following error message

`' err?: Error: Command failed with exit code 255: pulumi destroy --yes --skip-preview --exec-kind auto.inline --stack <stackname> --non-interactive\n' +`
`'error: failed to complete update: renewing lease: [403] The provided update token has expired.\n' +`

My application is running with the AKAMAI_ACCESS_TOKEN, AKAMAI_CLIENT_TOKEN, AKAMAI_CLIENT_SECRET and AKAMAI_HOST environment variables configured.

I haven't figured any way for me to refresh this update token while the program is running. Is there any way I can remedy this on my end?

### Expected Behavior

Expected the deactivation of the process to run its course and for pulumi to continue destroying the stack. Running pulumi destroy again after this error message successfully completes the process.

Would expect the library to refresh the token upon getting this exception.

### Steps to reproduce

- Create a new property and activate it in staging and production
- Destroy the stacks. Deactivation in production may take a long time to complete, and in this case the destruction of the stack throws an error message due to the pulumi update token having expired

### Output of `pulumi about`

Edit stack

% pulumi about
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.10.0'

Current Stack: theorganization/projectname/stackname

TYPE                                                URN
pulumi:pulumi:Stack                                 urn:pulumi:stackname::projectname::pulumi:pulumi:Stack::projectname-stackname
pkg:org:akamaigateway                            urn:pulumi:stackname::projectname::pkg:org:akamaigateway::subdomain
pulumi:providers:akamai                             urn:pulumi:stackname::projectname::pulumi:providers:akamai::default_4_1_0
akamai:index/edgeHostName:EdgeHostName              urn:pulumi:stackname::projectname::akamai:index/edgeHostName:EdgeHostName::subdomain.dev.domain.com
akamai:index/edgeHostName:EdgeHostName              urn:pulumi:stackname::projectname::akamai:index/edgeHostName:EdgeHostName::subdomain.domain.com
akamai:index/edgeHostName:EdgeHostName              urn:pulumi:stackname::projectname::akamai:index/edgeHostName:EdgeHostName::subdomain.test.domain.com
akamai:index/property:Property                      urn:pulumi:stackname::projectname::akamai:index/property:Property::subdomain.test.domain.com
akamai:index/property:Property                      urn:pulumi:stackname::projectname::akamai:index/property:Property::subdomain.dev.domain.com
akamai:index/property:Property                      urn:pulumi:stackname::projectname::akamai:index/property:Property::subdomain.domain.com
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.dev.domain.com
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.domain.com
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.test.domain.com
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-test-staging
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.test.domain.com.cname
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-dev-staging
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.dev.domain.com.cname
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-prod-staging
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:stackname::projectname::akamai:index/dnsRecord:DnsRecord::subdomain.domain.com.cname
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-test-production
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-dev-production
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:stackname::projectname::akamai:index/propertyActivation:PropertyActivation::subdomain-prod-production
akamai:index/appSecActivations:AppSecActivations    urn:pulumi:stackname::projectname::akamai:index/appSecActivations:AppSecActivations::appsecactivation-staging

Found no pending operations associated with theorganization/stackname

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/hanshe
User           hanshe
Organizations  hanshe, theorganization

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.46.0
@types/node     14.18.33

Pulumi locates its logs in /var/folders/jr/dvnd63wj11d_jrsk5y0qhr8r0000gn/T/ by default
warning: A new version of Pulumi is available. To upgrade from version '3.51.1' to '3.53.1', run 
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @Hanskun , thanks for bringing this up. Closing this as we have an issue in `pulumi/pulumi` to track this https://github.com/pulumi/pulumi/issues/7094
