### ISSUE TITLE
Problem destroying activated property in Akamai

### ISSUE THREAD

**Issue by Hanskun** [pulumi/pulumi-akamai#157]
### What happened?

When creating a property we use the akamai.DnsRecord resource to ad a cname record to the certStatus for certificate validation and renewal

![image](https://user-images.githubusercontent.com/278722/229052796-3a9ebe2c-6c4a-44a8-8d84-583d2d7af442.png)

This is causing an issue for us when we want to remove the property from Akamai. Doing a destroy of the stack we get the following error message

--- 

Diagnostics:
    akamai:index:PropertyActivation (abc):
    error: deleting urn:pulumi:stackname::project::akamai:index/propertyActivation:PropertyActivation::resource: 1 error occurred:
        * create deactivation failed: creating activation: API error:
    {
        "type": "https://problems.luna.akamaiapis.net/papi/v0/deactivation/property_deactivation_failed_hostname_cnamed_to_akamai",
        "title": "Property Deactivation Failed",
        "detail": "[Message{messageId=cannot_deactivate_hostname_cnamed_to_akamai, id=9ef579141eeee22350d538139178d7d291a7dd05, severity=ERROR, params=[thedomainname.com, thedomainname.com]}].",
        "instance": "https://akab-qgk4hlyqnk24mbgo-za343synxfly22si.luna.akamaiapis.net/papi/v1/properties/prp_123456/activations#eadf6426813d8a8e",
        "statusCode": 400
    }

---

To get around the issue we currently have to manually delete the DNS records in Akamai Control Center, and then do the stack destroy afterwards. This is not very practical in an automated solution, so I would appreciate any guidance to resolve the issue.

### Expected Behavior

When destroying the stack I would expect the provider to remove the DNS record and properly delete the property when the cname record has been deregistered

### Steps to reproduce

const property = new akamai.Property(`${subDomain}.${environmentDomain}`, {
    name: `${subDomain}.${environmentDomain}`,
    productId: productId,
    contractId: contractId,
    groupId: groupId,
    hostnames: [
        {
            cnameFrom: `${subDomain}.${environmentDomain}`,
            cnameTo: edgeHostname,
            certProvisioningType: "DEFAULT",
        },
    ],
    ruleFormat: "v2023-01-05",
    rules: rules,
});

const externalHostname = `${subDomain}.${environmentDomain}`;

new akamai.DnsRecord(`${subDomain}.${environmentDomain}`, {
    active: true,
    recordtype: "CNAME",
    ttl: 600,
    name: externalHostname,
    zone: `${environmentDomain}`,
    targets: [edgeHostname],
});

new akamai.DnsRecord(`${subDomain}.${environmentDomain}.cname`, {
    active: true,
    recordtype: "CNAME",
    ttl: 600,
    name: property.hostnames
        .apply((h) => (h ? h[0] : undefined))
        .apply((h) => (h ? h.certStatuses[0].hostname : "")),
    zone: `${environmentDomain}`,
    targets: [
        property.hostnames
            .apply((h) => (h ? h[0] : undefined))
            .apply((h) => (h ? h.certStatuses[0].target : "")),
    ],
});

### Output of `pulumi about`

% pulumi about
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.13.0'

Current Stack: elkjopnordic/gateways.local/hih-localapi

TYPE                                                URN
pulumi:pulumi:Stack                                 urn:pulumi:hih-localapi::gateways.local::pulumi:pulumi:Stack::gateways.local-hih-localapi
pkg:elkjop:akamaigateway                            urn:pulumi:hih-localapi::gateways.local::pkg:elkjop:akamaigateway::hihlocalapi
pulumi:providers:akamai                             urn:pulumi:hih-localapi::gateways.local::pulumi:providers:akamai::default_4_2_0
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:hih-localapi::gateways.local::akamai:index/dnsRecord:DnsRecord::hihlocalapi.elkjop.app
akamai:index/property:Property                      urn:pulumi:hih-localapi::gateways.local::akamai:index/property:Property::hihlocalapi.elkjop.app
akamai:index/dnsRecord:DnsRecord                    urn:pulumi:hih-localapi::gateways.local::akamai:index/dnsRecord:DnsRecord::hihlocalapi.elkjop.app.cname
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:hih-localapi::gateways.local::akamai:index/propertyActivation:PropertyActivation::hihlocalapi-prod-staging
akamai:index/propertyActivation:PropertyActivation  urn:pulumi:hih-localapi::gateways.local::akamai:index/propertyActivation:PropertyActivation::hihlocalapi-prod-production

Found no pending operations associated with elkjopnordic/hih-localapi

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/hanshe
User           hanshe
Organizations  hanshe, elkjopnordic

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.46.0
@types/node     14.18.33

Pulumi locates its logs in /var/folders/jr/dvnd63wj11d_jrsk5y0qhr8r0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Hanskun** [comment]
The CNAME issue is also occurring for the DNS record to the edge hostname as well

**Comment by guineveresaenger** [comment]
hi @Hanskun - this is [likely expected behavior for the Akamai API](https://community.akamai.com/customers/s/question/0D50f00006L0KBeCAN/is-there-any-possibility-to-overcome-cannotdeactivatehostnamecnamedtoakamai?language=en_US).

It may be your best bet to delete this property via the Akamai console, and then run `pulumi refresh`.

To avoid this in future, you should be able to make the PropertyActivation depend on your DNS record via [`dependsOn` Pulumi option.](https://www.pulumi.com/docs/intro/concepts/resources/options/dependson/).
