### ISSUE TITLE
Can an Akamai Property be imported/adopted through Pulumi?

### ISSUE THREAD

**Issue by victor-cui-discovery** [pulumi/pulumi-akamai#24]
I have an Akamai Property created manually that I would like to import (adopt) through Pulumi. From the [Pulumi docs](https://www.pulumi.com/docs/guides/adopting/import/) I know I can import an AWS resource into Pulumi (and I've tested it out), but can Pulumi do the same for an Akamai Property? If so what would the command look like?

**Comment by clstokes** [comment]
The latest version of the Pulumi Akamai provider (1.0.0) now supports this. 

```
pulumi import akamai:index/property:Property example prp_123
```

See https://www.pulumi.com/docs/reference/pkg/akamai/property/#import for more detail.
