### ISSUE TITLE
Pass version for akamai Property creation

### ISSUE THREAD

**Issue by mms-gianni** [pulumi/pulumi-akamai#294]
We are trying to manage our Akamai Properties with Pulumi. 

All our Pulumi-generated versions are based on version 1. We cannot create new versions based on a prior one. We miss a field to define it. (4dpw5.... is our Pulumi client)

![akamai_version_censored](https://github.com/pulumi/pulumi-akamai/assets/2052196/cdefaf62-4fa6-4a0f-be9c-e1644429f34a)

https://www.pulumi.com/registry/packages/akamai/api-docs/property/
```python
    prop = akamai.Property(configname,
        name=configname,
        contract_id=contract_id,
        group_id=group_id,
        product_id=product_id,
        hostnames=hostnames,
        rule_format=rule_format,
        rules=json.dumps(dpconfig),
    )
  ```

We see a "depends_on" field in the terraform implementation. But we are not sure if it does what we expect (creating a new version based on an old one) 
https://techdocs.akamai.com/terraform/docs/pm-rc-property 

pulumi==3.81.0
pulumi-akamai==6.2.0

**Comment by deepakjd2004** [comment]
Akamai terraform provider do not need version to be explicitly defined in property provider, it always picks up the code that you have in your codebase and push it to create new version. In case of Pulumi, when updating hostnames it somehow revert back changes to v1 always...

**Comment by iwahbe** [comment]
Sorry for not responding for so long, if this is still an issue:

I don't see any field on [upstream's docs](https://techdocs.akamai.com/terraform/docs/pm-rc-activation) that give the ability to set the depends on version, only the property version. `depends_on` (the resource option) is unrelated to the akamai property itself.

I would recommend filing an issue upstream with an enhancement request for a `depends_on_version` field.

If you believe there is a discrepancy between pulumi-akamai and the upstream terraform provider, can you please submit a Pulumi program that shows the pulumi-akamai's behavior and explain where it diverges from terraform-provider-akamai?
