### ISSUE TITLE
Conflicting rule validations for Origin Failure Recovery Methods

### ISSUE THREAD

**Issue by DiscoveryMike** [pulumi/pulumi-akamai#36]
I have a rules json with an empty array field and doing a pulumi up results in 

`error="updating rule tree: struct validation: Rules: (Rules: (Children: (3: (Behaviors: cannot be blank.).).).).
`

However, there are some rules block templates that can't have behaviors such as `Origin Failure Recovery Methods` where having a behavior set will result in a PAPI error:

`
{
        "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/generic_behavior_issue.recovery_method_rule_features_not_allowed",
        "title": "",
        "detail": "No behaviors are allowed directly under the 'Origin Failure Recovery Methods' rule template. ",
        "errorLocation": "#/rules/children/3/children/0/criteria/0"
    }
`

## Expected behavior

The schema for the rules json should match the papi's schema. Thus empty behavior arrays should be allowed for "Origin Failure Recovery Methods"

## Current behavior

"Origin Failure Recovery Methods" is failing before it hits PAPI with a schema validation error when the behaviors are empty but if they are filled with a blank filler rule, the PAPI enforces that it should be empty

## Steps to reproduce

1. Try to create an akamai property with "Origin Failure Recovery Methods" and provide empty top-level behaviors array

**Comment by jjgrinwis** [comment]
suffering from the same issue: error="updating rule tree: struct validation: Rules: (Rules: (Children: (0: (Behaviors: cannot be blank.);

pretty normal to have empty behaviors as it's used to make the delivery config more readable. The above error is part of the error seen when pushing the default created delivery configuration.

**Comment by jjgrinwis** [comment]
Looks like this is an underlying terraform issue:

https://github.com/akamai/terraform-provider-akamai/issues/194

This issue should be resolved in v1.2.1 release of the Terraform provider.
