### ISSUE TITLE
can't use CpCode.id resource in get_property_rules_template

### ISSUE THREAD

**Issue by jjgrinwis** [pulumi/pulumi-akamai#39]
when trying to use a CpCode resource id created via get_property_rules_template() call, the template call complains that it's an Output object and not one of the allowed values like a string. So we can't use a newly created cpcode resource with the get_property_rules_template() call. An existing code resource used via the get_cp_code() call is working fine so in the template, we can do stuff like this in the get_property_rules_template() call

```python
property_rules = akamai.get_property_rules_template(
    template_file=template_file,
    variables = [
        {
            'name':"cpCode",
            'value': int(cpcode.id.split('_')[1]),
            'type': "number",
        }
    ]
)
```

but we can't use the Output type as the value in this call.

## Expected behavior
We would like to use the expected id from the CpCode call in the get_property_rules_template() call so  "id": "${env.cpCode}" can be filled in the template.

## Current behavior
Pulumi throws an error, wrong type. We tried using the apply(lambda:) solution to wait for the rules to get build when a cpcode.id is available but then the problem moves to the Delivery resource as rules are invalid.

panic: invalid character 'D' after top-level value: 74D93920-ED26-11E3-AC10-0800200C9A66
    goroutine 12 [running]:
    github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property.compactJSON(0xc00030f9b0, 0x24, 0x30, 0xc00030f9b0, 0x24)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-akamai/v2@v2.0.0-20201230152346-7950a81711af/pkg/providers/property/provider.go:180 +0x1df

So a similar kind of issue. In this case the rules are not pointing to our json but an Output object

## Steps to reproduce
pulumu up

## Context (Environment)
We are trying to build a new delivery configuration that includes a new cpcode, hostname, and delivery resource. But template call will fail as cpcode is not available.

## Affected feature
Python with Akamai provider.
https://github.com/jjgrinwis/pulumi-property

**Comment by leezen** [comment]
I'm not sure if I'm 100% following, but if the issue is that you're trying to use the value of the `Output` within a template, you will want to construct the template within the `apply` of the `Output`, like so:

```python
def make_template(s):
    return akamai.get_property_rules_template(
        template_file=template_file,
        variables = [{
          'name':"cpCode",
          'value': int(s),
          'type': "number",
      }]
)

cpcode.id.apply(lambda s: make_template(s.split('_')[1]))
```

**Comment by jjgrinwis** [comment]
yes, that's working for the first step so it won't call the make_template until we have an id but the akamai.Property resource is expecting json in the rules section. So when we assign the output to a var or directly in the call like this:

```
prop = akamai.Property (
    property_name,
    contract_id = contract_id,
    group_id = group_id,
    product_id=product_id,
    name = property_name,
    rules = cpcode.id.apply(lambda s: make_template(s.split('_')[1])),
    hostnames = {
        property_name: edge_host.edge_hostname
    }
)
```
we get an error during preview stage probably because it's trying to use the object itself to create the json config:

panic: invalid character 'D' after top-level value: 74D93920-ED26-11E3-AC10-0800200C9A66
    goroutine 68 [running]:
    github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property.compactJSON(0xc013ad49f0, 0x24, 0x30, 0xc013ad49f0, 0x24)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-akamai/v2@v2.0.0-20201230152346-7950a81711af/pkg/providers/property/provider.go:180 +0x1df
    github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property.resourceProperty.func6(0x1dbc1c0, 0xc013b0ce60, 0x5, 0x1dbc1c0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-akamai/v2@v2.0.0-20201230152346-7950a81711af/pkg/providers/property/resource_akamai_property.go:182 +0x78

when we assign a static cpcode everything is working fine. It's the dynamic part of the cpcode resource that's giving issues when we want to use it in the template.

**Comment by leezen** [comment]
Shouldn't `rules = cpcode.id.apply(lambda s: make_template(s.split('_')[1]))` instead be:

`cpcode.id.apply(lambda s: make_template(s.split('_')[1])).json`?

If that doesn't help, if you can run this with [verbose logging](https://www.pulumi.com/docs/troubleshooting/), I can take a deeper look.

**Comment by jjgrinwis** [comment]
that's generating the same error with some extra debugging:

I0310 12:50:26.501341    3431 rpc.go:72] Marshaling property for RPC[Provider[akamai, 0xc000a00f60].Create(urn:pulumi:dev::cpcodes::akamai:index/property:Property::pulumi.grinwis.com).inputs]: name={pulumi.grinwis.com}
I0310 12:50:26.501345    3431 rpc.go:72] Marshaling property for RPC[Provider[akamai, 0xc000a00f60].Create(urn:pulumi:dev::cpcodes::akamai:index/property:Property::pulumi.grinwis.com).inputs]: productId={prd_Site_Accel}
I0310 12:50:26.501349    3431 rpc.go:72] Marshaling property for RPC[Provider[akamai, 0xc000a00f60].Create(urn:pulumi:dev::cpcodes::akamai:index/property:Property::pulumi.grinwis.com).inputs]: rules=output<string>{}
I0310 12:50:26.504345    3431 eventsink.go:78] eventSink::Infoerr(<{%reset%}>panic: invalid character 'D' after top-level value: 74D93920-ED26-11E3-AC10-0800200C9A66

I worked around it by using another stack where I create the cpcode and use the exported cpcode id from that stack in this stack.

```
other = pulumi.StackReference("jjgrinwis/cpcode/cpcode")
cpcode_id = other.get_output("cpcode_id").apply(lambda x: x.split('_')[1] )

property_rules = akamai.get_property_rules_template(
    template_file=template_file,
    variables = [
        {
            'name':"cpCode",
            'value': cpcode_id,
            'type': "number",
        }
   ]
)
```
So it's able to generate a valid configuration so we don't see any errors during the akamai.Property() call.
```
prop = akamai.Property (
    property_name,
    contract_id = contract_id,
    group_id = group_id,
    product_id=product_id,
    name = property_name,
    rules = property_rules.json,
    hostnames = {
        property_name: edge_host.edge_hostname
    }
)
```

**Comment by leezen** [comment]
Your workaround makes sense because at that point, the value is resolved. I realized a mistake I made in the above in that the .json should have been within the apply:

`cpcode.id.apply(lambda s: make_template(s.split('_')[1]).json)`

I wonder if that works for you?

**Comment by jjgrinwis** [comment]
that didn't make any difference. So now we're using another Pulumi project, export the value from that project and reuse them in this project, that's working fine.

**Comment by Milananas** [comment]
I'm running into this issue as well, the preferred solution would definitely be to use only one stack to provision the entire property, until then the multi-stack/project option offers a creative solution :-)

**Comment by iwahbe** [comment]
Hey @jjgrinwis. I'm sorry this issue has been around for so long. #36 has been solved, so I hope you have a working solution. If this issue is still bothering you, can you please open a new issue (or re-open this one) with a runnable self-contained reproduction of the issue.
