### ISSUE TITLE
error: could not read plugin resource-akamai-v2.0.0/pulumi-resource-akamai

### ISSUE THREAD

**Issue by jjgrinwis** [pulumi/pulumi-akamai#46]
when trying to use resource-akamai-v2.0.0 with pulumi>=3.0.0a1,<4.0.0 an error is thrown.

## Expected behavior
a pulumi up should be running a normal

## Current behavior
when running pulumi up

Diagnostics:
  pulumi:pulumi:Stack (cpcodes-dev):
    panic: strconv.ParseUint: parsing "": invalid syntax
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0xc0002bfab0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0.0/pkg/tfbridge/info.go:730 +0x1dc
    github.com/pulumi/pulumi-akamai/provider/v2.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/pulumi-akamai/pulumi-akamai/provider/resources.go:149 +0x17ca
    main.main()
        /home/runner/work/pulumi-akamai/pulumi-akamai/provider/cmd/pulumi-resource-akamai/main.go:27 +0x37

pulumi:providers:akamai (default):
    error: could not read plugin [/Users/username/.pulumi/plugins/resource-akamai-v2.0.0/pulumi-resource-akamai] stdout: EOF
 

## Steps to reproduce
When using the following packages:

pulumi>=3.0.0a1,<4.0.0
pulumi_akamai>=2.0.0

a pulumi up will always fail. 

When switching back to the previous packages everything working fine.
pulumi>=2.0.0,<3.0.0
pulumi_akamai>=1.3.0,<2.0.0

## Context (Environment)
just trying out the new providers on OSX

## Affected feature
pulumi_akamai

**Comment by stack72** [comment]
Hi @jjgrinwis 

Looking into this right now

P.

**Comment by stack72** [comment]
Hey @jjgrinwis 

Ok, I have just pushed a new tag that fixes this - it will take about 17 mins to deploy

https://github.com/pulumi/pulumi-akamai/actions/runs/768356831

I will close the issue out when this has been deployed and you are happy with it

Paul

**Comment by stack72** [comment]
Hey @jjgrinwis 

I believe this is now taken care of - please can you try this again?

Paul

**Comment by jjgrinwis** [comment]
Hi @stack72,

that's working again with these new packages:

Installing collected packages: pulumi, pulumi-akamai
Successfully installed pulumi-3.1.0a1618872113 pulumi-akamai-2.0.1

No more panics so the issue can be closed.

**Comment by stack72** [comment]
Thanks so much for verifying! Sorry this appened
