### ISSUE TITLE
ERROR] could not read property version

### ISSUE THREAD

**Issue by jjgrinwis** [pulumi/pulumi-akamai#50]
When making a small change to the config and trying to run plumumi up again to apply the change, update is failing with following error:

2021/04/30 11:48:05 [ERROR] could not read property version: OperationID=68ff2738-a72d-4772-9d1a-dea8f7b59701 PAPI=resourcePropertyUpdate property_name=prp_692721 contract_id=ctr_C-1IE2OHM error="fetching property version: struct validation: PropertyVersion: cannot be blank." group_id=grp_67223 property_version=0

## Expected behavior
pulumi up should just push this change to the config.

## Current behavior
We can create a working property and activate it on staging and production all working fine.
But when we change just the TTL in the rules.json and try to push it again it fails to update the configuration.

## Steps to reproduce
https://github.com/jjgrinwis/pulumi-property/blob/master/__main__.py

initial version v1 created and pushed to staging and prod, all working fine.
But after changing ttl to 2h in our rules config.

$ pulumi up

2021/04/30 11:48:05 [ERROR] could not read property version: OperationID=68ff2738-a72d-4772-9d1a-dea8f7b59701 PAPI=resourcePropertyUpdate property_name=prp_692721 contract_id=ctr_C-1IE2OHM error="fetching property version: struct validation: PropertyVersion: cannot be blank." group_id=grp_67223 property_version=0
 
  akamai:index:Property (pulumi.grinwis.com):
    error: 1 error occurred:
        * updating urn:pulumi:dev::cpcodes::akamai:index/property:Property::pulumi.grinwis.com: 1 error occurred:
        * fetching property version: struct validation: PropertyVersion: cannot be blank.
        * provider_plugin.go:1391] provider received rpc error `Unknown`: `updating urn:pulumi:dev::cpcodes::akamai:index/property:Property::pulumi.grinwis.com: 1 error occurred:
        * fetching property version: struct validation: PropertyVersion: cannot be blank.

## Context (Environment)
basic functionality, just trying to update a config.

## Affected feature
basic update request

**Comment by jjgrinwis** [comment]
Just did a Terraform test and looks like the wrong property_version is being used when using Pulumi. Terraform using the correct latest_version which is 1 in the first run and is updated after we pushed an updated config to staging again:

2021-05-07T18:57:29.227+0200 [DEBUG] provider.terraform-provider-akamai_v1.5.1: 2021/05/07 06:57:29 [DEBUG] fetching property version: OperationID=d3bbf1f6-ed0d-46cc-9f81-4a3147973817 PAPI=resourcePropertyRead contract_id=ctr_C-1IE2OHM group_id=grp_67223 **property_version=2** property_name=prp_708660
2021-05-07T18:57:29.227+0200 [DEBUG] provider.terraform-provider-akamai_v1.5.1: 2021/05/07 06:57:29 [DEBUG] GetPropertyVersion: OperationID=d3bbf1f6-ed0d-46cc-9f81-4a3147973817
2021-05-07T18:57:30.434+0200 [DEBUG] provider.terraform-provider-akamai_v1.5.1: 2021/05/07 06:57:30 [DEBUG] property version fetched: OperationID=d3bbf1f6-ed0d-46cc-9f81-4a3147973817 PAPI=resourcePropertyRead property_id=prp_708660 product_id=prd_SPM contract_id=ctr_C-1IE2OHM group_id=grp_67223 **property_version=2** property_name=prp_708660

So have never seen the property_version=0 when testing with Terraform.

**Comment by jjgrinwis** [comment]
just tested the latest pulumi_akamai provider 2.2.0, still the same issue:

2021/05/27 03:04:47 [ERROR] could not read property version: OperationID=7f998fd9-fde4-46cd-8018-49cf74039657 PAPI=resourcePropertyUpdate property_version=0 property_name=prp_712926 contract_id=ctr_3-16TWBVX group_id=grp_48668 error="fetching property version: struct validation: PropertyVersion: cannot be blank.

**Comment by stack72** [comment]
Hey @jjgrinwis 

Sorry, this wasn't in the latest release - this is on my list to fix in the next few days!

Paul

**Comment by jjgrinwis** [comment]
any idea when this issue will be resolved?

**Comment by stack72** [comment]
Hi @jjgrinwis 

My apologies this slipped - I will make sure and reprioritise this and ensure it will be taken care of as part of the upgrade to the provider

Paul

**Comment by stack72** [comment]
Hi @jjgrinwis 

I just releases of 2.3.0 of the pulumi-akamai provider - can you tell me if this issue still persists with the latest version of the provider since it's had version changes upstream

Thanks

Paul

**Comment by jjgrinwis** [comment]
Hi Paul,

still the same problem:

error: update failed
 
    2021/08/19 02:35:36 [ERROR] could not update property rules: OperationID=0db0c5c9-4559-4681-bd3c-194b41dfbde8 PAPI=resourcePropertyUpdate validate_rules=true property_id=prp_734175 group_id=grp_67223 error="updating rule tree: struct validation: PropertyVersion: cannot be blank." contract_id=ctr_C-1IE2OHM property_version=0 validate_mode=
 
  akamai:index:Property (pulumi-latest.grinwis.com):
    error: 1 error occurred:
        * updating urn:pulumi:dev::pulumi-property::akamai:index/property:Property::pulumi-latest.grinwis.com: 1 error occurred:
        * updating rule tree: struct validation: PropertyVersion: cannot be blank.

So creating initial config/edgehosts all fine. Then making a config change like update cache setting in the akamai config file, running pulumi up again and things go wrong.

% pulumi version
v3.10.3
% pip freeze | grep pulumi
pulumi==3.10.3
pulumi-akamai==2.3.0

**Comment by jjgrinwis** [comment]
Looks like something is going wrong with the mapping of the "real" version numbers to pulumi data structure. 
Versions according to the created Akamai property resource as seen by Pulumi:

pulumi.export("latest_version", prop.latest_version)
pulumi.export("staging_version", prop.staging_version)
pulumi.export("production_version", prop.production_version)

Outputs:
    latest_version    : 1
    production_version: **0**
    staging_version   : **0**

the "real" versions active on Akamai:
{
  "groupId": "grp_67223",
  "propertyId": "prp_734175",
  "propertyName": "pulumi-latest.grinwis.com",
  "latestVersion": 1,
  "stagingVersion": **1**,
  "productionVersion": **1**,
  "assetId": "aid_10941650"
}

I0819 23:52:24.875989   11521 eventsink.go:78] eventSink::Infoerr(<{%reset%}>2021/08/19 11:52:24 [ERROR] could not create new property version: OperationID=2bfb23b8-0797-4a08-bf7e-0f41c466b3fb PAPI=resourcePropertyUpdate error="creating property version: struct validation: Version: (CreateFromVersion: cannot be blank.)." group_id=grp_67223 from_property_version=0 property_id=prp_734175 contract_id=ctr_C-1IE2OHM
<{%reset%}>)
I0819 23:52:24.882640   11521 provider_plugin.go:1523] provider received rpc error `Unknown`: `updating urn:pulumi:dev::pulumi-property::akamai:index/property:Property::pulumi-latest.grinwis.com: 1 error occurred:
        * creating property version: struct validation: Version: (CreateFromVersion: cannot be blank.).

**Comment by Milananas** [comment]
Any updates? Running into this issue as well.

**Comment by nipun45** [comment]
Any updates? Im also getting similar error "CreateFromVersion: cannot be blank" when trying to update akamai property.

```
2022/06/30 01:13:53 [ERROR] could not create new property version: OperationID=6a98a0d0-9e63-447a-8dda-233d0169bfb8 PAPI=resourcePropertyUpdate from_property_version=0
      error=
      | creating property version: struct validation:
      | CreateFromVersion: cannot be blank
       property_id=prp_812487 contract_id=ctr_G-2TTUIGH group_id=grp_152682
 
    error: update failed
```
