### ISSUE TITLE
Upgrade to v1.6.1 of the Akamai Terraform Provider

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-akamai#55]

**Comment by jjgrinwis** [comment]
Hi Paul, do you have any idea when a new version of the provider is going to be released?

**Comment by stack72** [comment]
Hey @jjgrinwis 

I actually pinged you on email to see if you could help me test something or take me through making our Akamai testing environment a little better to test out the upgrade

If you are able to help I'd love to schedule some time next week as I want to be able to fix this up for you

Paul

**Comment by jjgrinwis** [comment]
Hi Paul, no problem. Just sent you an email with contact details.

John
